name: WordPress Deployment

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v2

- name: Set up SSH
uses: webfactory/ssh-agent@v0.5.0
with:
ssh-private-key: ${{ secrets.github }}

- name: Install dependencies
run: |
# Add any commands to install dependencies here

- name: Transfer files to EC2 instance
run: |
# Add commands to transfer files to your EC2 instance using SSH
# For example: scp -r /home/ubuntu/wordpress*/ ubuntu@13.234.76.98:/var/www/html

- name: Deploy WordPress
run: |
# Add any deployment scripts or commands here
has context menu
