name: Deploy to EC2

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
- name: 
    -Checkout code
uses: actions/checkout@v2

run: |
mkdir -p ~/.ssh
echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
ssh-keyscan -H 13.234.76.98 >> ~/.ssh/known_hosts

- name: Copy WordPress setup files to EC2
run: scp -r /home/ubuntu/wordpress*/ ubuntu@13.234.76.98:/var/www/html
has context menu
